server:
  port: 8080

spring:

  datasource:
    url: ${YOEDU_DB_URL:jdbc:mysql://localhost:3306/yoot_management_db?createDatabaseIfNotExist=true}
    username: ${YOEDU_DB_USERNAME:root}
    password: ${YOEDU_DB_PASSWORD:dev}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


app:
  jwt:
    issuer: yoedu-demo
    secret: qv!!a?6ct7tM;2{:tkJ*vvP(4P7f}%PZ
    access-token-ttl-minutes: 480
    refresh-token-ttl-days: 7